sudo : enable
language : C
script : 
        - sudo apt install libsfml-dev
        - mkdir build
        - cd build
        - cmake .. 
        - make
        - ./networkTest -s &
        - ./networkTest -c
